PGMs := DSPUSR.PGM DSPUSR2.PGM DSPUSR3.PGM DSPUSR4.PGM
DSPUSR.PGM:    $(d)/DSPUSR.PGM.SQLRPGLE
DSPUSR2.PGM:    $(d)/DSPUSR2.PGM.RPGLE
DSPUSR3.PGM:    $(d)/DSPUSR3.PGM.SQLRPGLE
DSPUSR4.PGM:    $(d)/DSPUSR4.PGM.SQLRPGLE


