PGMs := WS1USR.PGM WS2SQL.PGM WS3DTAS.PGM WS4VARCH.PGM TESTPGM.PGM
WS1USR.PGM:    $(d)/WS1-DSPUSR.PGM.RPGLE
WS2SQL.PGM:    $(d)/WS2-SQL-USR2.PGM.SQLRPGLE
WS3DTAS.PGM:    $(d)/WS3-DTAS.PGM.SQLRPGLE
WS4VARCH.PGM:    $(d)/WS4-VARCH.PGM.SQLRPGLE
TESTPGM.PGM: $(d)/TESTPGM.PGM.RPGLE


