PGMs := DSPUSR.PGM DSPUSR2.PGM DSPUSR3.PGM DSPUSR4.PGM HELLOWORLD.PGM
DSPUSR.PGM:    $(d)/DSPUSR.PGM.RPGLE
DSPUSR2.PGM:    $(d)/DSPUSR2.PGM.SQLRPGLE
DSPUSR3.PGM:    $(d)/DSPUSR3.PGM.SQLRPGLE
DSPUSR4.PGM:    $(d)/DSPUSR4.PGM.SQLRPGLE
HELLOWORLD.PGM: $(d)/HELLOWORLD.PGM.RPGLE


